### ISSUE TITLE
Lorenz drawing a bit out of scale

### ISSUE THREAD

**Issue by The-Great-Assyr** [baconpaul/mschack-VCV-Rack-Plugins#20]
![capture_001_25082023_141246](https://github.com/baconpaul/mschack-VCV-Rack-Plugins/assets/35512040/1ae3a016-8db8-4b76-a952-f7cef0582db3)
Hello there and friendly greetings! I actually don't know if the Lorenz module is supposed to behave like that. It works, don't get me wrong, but the graph as you can see is a bit out of scale and out of module.
I hope this could be useful. Have a great day!

**Comment by baconpaul** [comment]
Ha well clearly not.

does it always do that for you? Or just at some settings?

I wonder if that code deals improperly with rack zoom also

thanks
